on:
  workflow_call:
    inputs:

## this would be nice
# defaults:
#   run:
#     shell: bash
#     working-directory: ./frontend

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.29.3' 
        channel: 'stable'
    - run: |
        echo hi
      shell: bash
    - name: install dependencies and run code gen
      run: |
        flutter pub get #make sure this path is correct
        flutter pub run intl_utils:generate
      shell: bash

